#!/bin/bash
echo "Which block device would you like to mount e.g. sdb8: "
read sdxx
mount /dev/$sdxx /mnt/
mount -t proc none /mnt/proc
mount -o bind /dev /mnt/dev
mount -t sysfs sys /mnt/sys
mkdir -p /mnt/boot/efi
mount /dev/sdb1 /mnt/boot/efi
mkdir /mnt/hostlvm
mount --bind /run/lvm /mnt/hostlvm
echo "Enter: ln -s /hostlvm /run/lvm"
echo "Enter: grub-install"
echo "Enter: update-grub"
echo "Enter: exit"
chroot /mnt/ /bin/bash
umount /mnt/boot/efi
umount /mnt/hostlvm
umount /mnt/sys
umount /mnt/dev
umount /mnt/proc
umount /mnt
echo "Process complete!"
